using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using EgitimKayitLib;
using System.Text.RegularExpressions;

namespace EgitimKayitLib.Tests
{
    [TestClass]
    public class DersClass_Should
    {
        [TestMethod]
        public void HaveAutogeneratedId()
        {
            //Arrange
            var dersAdi = "Test Ders";

            //Act
            Ders ders = new Ders(dersAdi);

            //Assert
            Assert.IsNotNull(ders.Id);
        }

        [TestMethod]
        public void HaveAGuidId()
        {

            //Arrange
            var dersAdi = "Test Ders";

            //Act
            Ders ders = new Ders(dersAdi);
            Regex guidRegEx = new Regex(@"^(\{{0,1}([0-9a-fA-F]){8}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){12}\}{0,1})$");

            //Assert
            Assert.IsTrue(guidRegEx.IsMatch(ders.Id));
        }
    }
}
